### ISSUE TITLE
add docker sync support

### ISSUE THREAD

**Issue by benrowe** [benrowe/docker-template#1]
docker-sync.yml
```
version: "2"
options:
  compose-file-path: '/ops/docker-compose.yml'
  verbose: false
  max-attempt: 5
syncs:
  appname-app-sync:
    src: './'
    sync_strategy: 'unison'
    sync_userid: 1000
    sync_excludes: ['.gitignore', 'node_modules', '.circleci', '.docker-sync', 'cypress', 'ops', 'resources/assets', '.idea', '.git']
    watch_excludes: ['node_modules', '.git', '.idea']
```
update compose
```
volumes:
  db_data:
  redis_data:
  appname-app-sync:
    external: true
```
volumes
`- appname-app-sync:/code:nocopy`

php dockerfile
```
RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
RUN apk --no-cache add shadow && usermod -u 1000 www-data
```

nginx dockerfile
RUN adduser -D -H -u 1000 -s /bin/bash www-data
